### ISSUE TITLE
Plasma can use wrong sprite when dryfiring

### ISSUE THREAD

**Issue by Pink-Silver** [XaserAcheron/argent#58]
Equip the Plasma Gun with a Stun Bomb attachment, then use enough cells so you can't fire the stun bomb and try to alt-fire. The plasma changes sprites and uses the standard idle sprite instead.

**Comment by XaserAcheron** [comment]
Heh! This is funny for some reason. Hooray metamorph mode!

Thanks for the report. Will fix once I'm done fiddling with my present project (Gauss Siege Mode O:)
