### ISSUE TITLE
Lock-On Burst doesn't work at long range

### ISSUE THREAD

**Issue by XaserAcheron** [XaserAcheron/argent#61]
Welp. I suspect this is because the player's built-in target acquisition peters out after (IIRC) 1024 units. D:

I'll revisit this post-zscript-conversion. I'm limited in options now.

**Comment by Pink-Silver** [comment]
https://github.com/Kyle873/DoomRPG/blob/master/DoomRPG/scripts/Utils.c#L872

I'll leave this here since it'll be useful to you for solving this issue using some ACS trickery like we did there. I wrote the function because of this problem.

**Comment by XaserAcheron** [comment]
Forgot to close this one -- thanks muchly for the script donation, but ZScript upped the ante and allowed me to call AimLineAttack directly, solving the problem. Egad! O_O
